import { Brand } from './types';
import logoBrand from '@/assets/logo-brand.avif';

export const featuredBrands: Brand[] = [
  {
    id: 'dinnus-kids',
    name: 'Dinnus Kids',
    logo: logoBrand,
    description: 'Moda infantil básica e confortável',
    isActive: true,
    productCount: 45,
    location: 'Petrolina - PE',
    instagram: 'https://www.instagram.com/dinnuskids',
    category: 'clothing',
    gender: 'meninos',
    partnershipLevel: 'gold',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'dafeto',
    name: "D'Afeto",
    logo: logoBrand,
    description: 'Acessórios e vestidos estampados',
    isActive: true,
    productCount: 38,
    location: 'Petrolina - PE',
    instagram: 'https://www.instagram.com/dafetoatacadoinfantil',
    category: 'accessories',
    gender: 'meninas',
    partnershipLevel: 'silver',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'toninho-kids',
    name: 'Toninho Kids',
    logo: logoBrand,
    description: 'Camisas e bermudas para meninos',
    isActive: true,
    productCount: 32,
    location: 'Moda Center Santa Cruz',
    instagram: 'https://www.instagram.com/toninhokids',
    category: 'clothing',
    gender: 'meninos',
    partnershipLevel: 'bronze',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'charminho',
    name: 'Charminho',
    logo: logoBrand,
    description: 'Vestidos e conjuntos arrumados',
    isActive: true,
    productCount: 28,
    location: 'Gravatá - PE',
    instagram: 'https://www.instagram.com/charminhomodainfantil',
    category: 'clothing',
    gender: 'meninas',
    partnershipLevel: 'gold',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'gritty-teen',
    name: 'Gritty Moda Teen',
    logo: logoBrand,
    description: 'Moda praia e vestidos estampados',
    isActive: true,
    productCount: 25,
    location: 'Moda Center Santa Cruz',
    instagram: 'https://www.instagram.com/grittymodateen',
    category: 'clothing',
    gender: 'meninas',
    partnershipLevel: 'silver',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'mini-dylla',
    name: 'Mini Dylla',
    logo: logoBrand,
    description: 'Moda bebê e calçados',
    isActive: true,
    productCount: 42,
    location: 'Online',
    website: 'https://www.minidylla.com.br/',
    instagram: 'https://instagram.com/minidylla',
    category: 'mixed',
    gender: 'unisex',
    partnershipLevel: 'gold',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'fump-kids',
    name: 'FUMP Kids',
    logo: logoBrand,
    description: 'Moda infantil premium',
    isActive: true,
    productCount: 55,
    location: 'Moda Center Santa Cruz',
    website: 'https://usefumpkids.com.br/',
    instagram: 'https://instagram.com/fump_oficial',
    category: 'clothing',
    gender: 'meninos',
    partnershipLevel: 'gold',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'begkids',
    name: 'BEGKIDS',
    logo: logoBrand,
    description: 'Vestidos e conjuntos estampados',
    isActive: true,
    productCount: 35,
    location: 'Moda Center Santa Cruz',
    website: 'https://begkids.fazagilizar.com.br/',
    instagram: 'https://www.instagram.com/atacadobegkids',
    category: 'clothing',
    gender: 'meninas',
    partnershipLevel: 'silver',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'koli',
    name: 'KOLI',
    logo: logoBrand,
    description: 'Moda básica para meninos',
    isActive: true,
    productCount: 30,
    location: 'Online',
    instagram: 'https://www.instagram.com/koli.time',
    category: 'clothing',
    gender: 'meninos',
    partnershipLevel: 'bronze',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'rck',
    name: 'RCK',
    logo: logoBrand,
    description: 'Camisas e bermudas masculinas',
    isActive: true,
    productCount: 22,
    location: 'Moda Center Santa Cruz',
    instagram: 'https://instagram.com/rck_modainfantil',
    category: 'clothing',
    gender: 'meninos',
    partnershipLevel: 'bronze',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'estilosinhos',
    name: 'Estilosinhos',
    logo: logoBrand,
    description: 'Vestidos e conjuntos estampados',
    isActive: true,
    productCount: 18,
    location: 'Moda Center Santa Cruz',
    instagram: 'https://www.instagram.com/estilosinhosmodakids',
    category: 'clothing',
    gender: 'meninas',
    partnershipLevel: 'bronze',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'espaco-kids-prime',
    name: 'Espaço Kids Prime',
    logo: logoBrand,
    description: 'Moda completa para meninas e meninos',
    isActive: true,
    productCount: 40,
    location: 'Moda Center Santa Cruz',
    instagram: 'https://instagram.com/espacokidsprime',
    category: 'mixed',
    gender: 'unisex',
    partnershipLevel: 'silver',
    featuredUntil: '2024-12-31'
  },
  {
    id: 'tigrom',
    name: 'TIGROM',
    logo: logoBrand,
    description: 'Moda básica e confortável',
    isActive: true,
    productCount: 35,
    location: 'Moda Center Santa Cruz',
    instagram: 'https://instagram.com/ttigrom',
    category: 'clothing',
    gender: 'meninos',
    partnershipLevel: 'bronze',
    featuredUntil: '2024-12-31'
  }
]; 